/* Gee Haven AI Sprite - typing chat. It recommends from the current menu data. */
(function(){
function esc(s){return String(s??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function menu(){return (Array.isArray(window.GEE_MENU_ITEMS)?window.GEE_MENU_ITEMS:[]).filter(x=>x.is_available!==false);}
function score(x,q){const t=`${x.name||""} ${x.description||""} ${x.category||""}`.toLowerCase(),w=q.toLowerCase();let n=0;const groups=[[['鸡','chicken'],['chicken','鸡']], [['牛','beef'],['beef','牛']], [['猪','pork'],['pork','猪']], [['肉','meat'],['meat','chicken','beef','pork','肉']], [['鱼','fish'],['fish','鱼']], [['虾','prawn','shrimp'],['prawn','shrimp','seafood','虾']], [['饭','rice','nasi'],['rice','nasi','饭']], [['汤','soup'],['soup','汤']], [['甜','dessert','sweet'],['dessert','sweet','pudding','mango','甜']], [['喝','饮料','drink','tea'],['drink','tea','lemon','饮料']], [['辣','spicy'],['spicy','辣']]];groups.forEach(([keys,tags])=>{if(keys.some(k=>w.includes(k))&&tags.some(k=>t.includes(k)))n+=8;});const m=w.match(/(?:rm|r\$)\s*(\d+(?:\.\d+)?)/i);if(m&&Number(x.price)<=Number(m[1]))n+=5;if(/便宜|cheap|budget|以内|低于/.test(w)&&Number(x.price)<=20)n+=3;if(/贵|premium|高级/.test(w)&&Number(x.price)>=20)n+=2;return n;}
function recommendations(q){const a=menu().map(x=>({...x,_score:score(x,q)})).sort((a,b)=>b._score-a._score);return a.filter(x=>x._score>0).slice(0,3).concat(a.filter(x=>x._score===0).slice(0,3)).slice(0,3);}
function add(text,who='bot',html=false){const c=document.getElementById('aiChat');if(!c)return;const d=document.createElement('div');d.className='ai-msg '+who;html?d.innerHTML=text:d.textContent=text;c.appendChild(d);c.scrollTop=c.scrollHeight;}
function send(){const i=document.getElementById('aiInput'),q=i.value.trim();if(!q)return;i.value='';add(q,'user');setTimeout(()=>{const m=menu();if(!m.length){add('我现在还没有读取到 Gee Haven 的菜单。请先打开 Menu 页面，我就可以根据最新菜单帮你推荐 😊');return;}if(/^(hi|hello|你好|嗨|hey)$/i.test(q)){add('你好～🧚 我是 Gee Haven AI 精灵！你可以直接打字告诉我想吃什么、喜欢什么口味或预算，我会从菜单里帮你找。');return;}const r=recommendations(q);if(!r.length){add('目前没有找到符合你描述的菜品。试试告诉我「我想吃鸡肉」、「有没有甜点」或「RM20以内有什么？」');return;}add('我帮你从 Gee Haven 的菜单找到了这些：');r.forEach(x=>add(`<div class="ai-rec"><div class="ai-rec-top"><b>${esc(x.name)}</b><strong>${money(x.price)}</strong></div><p>${esc(x.description||'Gee Haven 菜单精选。')}</p><p><b>分类：</b>${esc(x.category||'Other')}</p><p><b>推荐：</b>根据你刚才说的口味/预算匹配。</p><button class="btn ai-add" data-id="${esc(x.id)}">🛒 加入购物车</button></div>`,'bot',true));document.querySelectorAll('.ai-add').forEach(b=>b.onclick=()=>{if(typeof window.addToCart==='function'){window.addToCart(b.dataset.id);add('已经帮你加入购物车啦！🛒');}});},300);}
function open(){document.getElementById('aiPanel').classList.remove('hidden');const c=document.getElementById('aiChat');if(!c.children.length){add('嗨！我是 Gee Haven AI 精灵 🧚');add('今天想吃什么？直接打字告诉我就可以，例如「我想吃肉的，RM20以内」。');}setTimeout(()=>document.getElementById('aiInput')?.focus(),50);}
function init(){if(document.getElementById('aiSprite'))return;document.body.insertAdjacentHTML('beforeend',`<button id="aiSprite" class="ai-sprite" type="button"><span>🧚</span><b>AI 精灵</b><small>问问我</small></button><section id="aiPanel" class="ai-panel hidden"><div class="ai-head"><div><div class="ai-title">🧚 Gee Haven AI 精灵</div><div class="ai-subtitle">像现在聊天一样直接打字</div></div><button id="aiClose" class="modal-close" type="button">×</button></div><div id="aiChat" class="ai-chat"></div><div class="ai-typing"><input id="aiInput" placeholder="例如：我想吃鸡肉，RM20以内"><button id="aiSend" class="btn" type="button">发送</button></div><div class="ai-suggestions"><button data-q="我想吃肉">🥩 我想吃肉</button><button data-q="有没有甜点？">🍰 有没有甜点？</button><button data-q="RM20以内有什么？">💰 RM20以内</button></div></section>`);document.getElementById('aiSprite').onclick=open;document.getElementById('aiClose').onclick=()=>document.getElementById('aiPanel').classList.add('hidden');document.getElementById('aiSend').onclick=send;document.getElementById('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')send();});document.querySelectorAll('.ai-suggestions button').forEach(b=>b.onclick=()=>{document.getElementById('aiInput').value=b.dataset.q;send();});}
document.addEventListener('DOMContentLoaded',init);})();
